version: '3.8'

services:
  music-bot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: telegram-music-bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - ./temp_audio:/app/temp_audio
      - ./track_cache.json:/app/track_cache.json
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
